services:
  regfab:
    image: regfab
    build:
      context: ./
      dockerfile: Containerfile
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ./data:/regfab/data
    ports:
      - 8000:8000